import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Importing Poppins from Google Fonts
const poppins = Poppins({
  // src: "./fonts/Poppins-Regular.ttf",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

// Local font imports
const helveticaNow = localFont({
  src: "./fonts/HelveticaNowDisplay.woff",
  variable: "--font-helvetica-now-display",
  weight: "100 200 300 400 500 600 700 800 900",
});

const TTChocolates = localFont({
  src: "./fonts/TTChocolatesRegular.otf",
  variable: "--font-tt-chocolates",
  weight: "400 500 600 700"
})

// Metadata
export const metadata = {
  title: "Virtual Guru",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${helveticaNow.variable} ${TTChocolates.variable} font-tt-chocolates antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
